
DROP DATABASE IF EXISTS BD_HURON_AZUL;
CREATE DATABASE BD_HURON_AZUL;
USE BD_HURON_AZUL;

CREATE TABLE USUARIO (
    CODUSUARIO BIGINT PRIMARY KEY AUTO_INCREMENT,
    NOMUSUARIO VARCHAR(100) NOT NULL,
    APEUSUARIO VARCHAR(100) NOT NULL,
    DIRECCION VARCHAR(200),
    DNI CHAR(8) NOT NULL,
    SEXO INT NOT NULL,
    FECNAC DATE NOT NULL,
    EMAIL VARCHAR(100),
    TELEFONO VARCHAR(20),
    IDLOGIN VARCHAR(100) NOT NULL,
    PASSWORD CHAR(10) NOT NULL,
    TIPOUSUARIO INT DEFAULT 2 NOT NULL,
    ESTADO BIT DEFAULT 1 NOT NULL
);
INSERT INTO USUARIO(NOMUSUARIO,APEUSUARIO,DIRECCION,DNI,SEXO,FECNAC,EMAIL,TELEFONO,IDLOGIN,PASSWORD,TIPOUSUARIO) VALUES
('HUMBERTO','REINOSO','UV MIRONES BLOCK 5B LIMA CERCADO','73580887',1,'19930601','HDRF1993@OUTLOOK.COM','944809183','HREINOSO','1234567890',1),
('JUAN','PACHECO','PASAJE UDIMA 160-B','45984522',1,'19930612','AERO356@GMAIL.COM','944809183','AEROMAN','0123456789',2),
('DIANA','LAOS','AV CENTRAL 210 SAN MARTIN DE PORRES','78894561',2,'19930128','DLAOS@GMAIL.COM','945276774','DLAOS','DLAOSDLAOS',2);
SELECT 
    *
FROM
    USUARIO;

CREATE TABLE PRODUCTO (
    CODPROD BIGINT PRIMARY KEY AUTO_INCREMENT,
    DESCPROD VARCHAR(100) NOT NULL,
    PREPROD NUMERIC(19 , 6 ) NOT NULL,
    STKPROD INT DEFAULT 0 NOT NULL,
    FOTOPROD VARCHAR(100),
    CATPROD BIGINT NOT NULL
);
INSERT INTO PRODUCTO(DESCPROD,PREPROD,STKPROD,FOTOPROD,CATPROD) VALUES
('MISCOZOO',17.00,100,'PROD1.JPEG',1),
( 'MISCOBONES',17.00,100,'PROD2.JPEG',1),
( 'MISCODENTAL' , 17.00,100,'PROD3.JPEG',1),
( 'MISCODUO', 17.00,100,'PROD4.JPEG',1),
( 'MISCOSOFT SALMON' , 17.00,100,'PROD5.JPEG',1),
( 'MISCOSTICK CHICKEN',17.00,0,'PROD6.JPEG',1),
( 'MISCOTOFFY SALMON' ,17.00,0,'PROD7.JPEG',1);
SELECT 
    *
FROM
    PRODUCTO;

CREATE TABLE CATEGORIAPROD (
    CODCAT BIGINT PRIMARY KEY AUTO_INCREMENT,
    DESCCAT VARCHAR(100) NOT NULL
);
INSERT INTO CATEGORIAPROD(DESCCAT) VALUES ('ALIMENTOS'),('JUGUETES'),('MEDICAMENTOS'),('UTENSILIOS')
;
SELECT 
    *
FROM
    CATEGORIAPROD;

CREATE TABLE PEDIDO (
    CODPEDIDO BIGINT PRIMARY KEY AUTO_INCREMENT,
    CLIENTE BIGINT NOT NULL,
    FECPEDIDO DATETIME NOT NULL,
    SEDE BIGINT NOT NULL,
    METODOENVIO INT NOT NULL,
    METODOPAGO INT NOT NULL,
    MONTO NUMERIC(19 , 6 ) NOT NULL
);
INSERT INTO PEDIDO(CLIENTE,FECPEDIDO,SEDE,METODOENVIO,METODOPAGO,MONTO) VALUES 
(2,'2019-11-04 15:25',1,1,1,85),
(2,'2019-11-05 10:26',2,1,1,34),
(3,'2019-11-26 17:20',1,2,1,17),
(3,'2019-11-28 14:02',2,1,1,17);
SELECT 
    *
FROM
    PEDIDO;

CREATE TABLE PEDIDODETALLE (
    CODPEDIDO BIGINT NOT NULL,
    PRODUCTO BIGINT NOT NULL,
    CANTIDAD INT NOT NULL,
    MONTO NUMERIC(19 , 6 ) NOT NULL,
    PRIMARY KEY (CODPEDIDO , PRODUCTO)
);
INSERT INTO PEDIDODETALLE VALUES 
(1,1,2,34),(1,3,3,51),
(2,1,1,17),(2,3,1,17),
(3,2,1,17),
(4,2,1,17);
SELECT 
    *
FROM
    PEDIDODETALLE;

CREATE TABLE SEDE (
    CODSEDE BIGINT PRIMARY KEY AUTO_INCREMENT,
    REFSEDE VARCHAR(100) NOT NULL,
    DIRSEDE VARCHAR(200)
);
INSERT INTO SEDE(REFSEDE,DIRSEDE) VALUES
('SAN MIGUEL - F. GALLESE','AV. FEDERICO GALLESE 301'),
('SAN MIGUEL - INSURGENTES','AV INSURGENTES 842'),
('PUEBLO LIBRE','AV SUCRE 340'),
('CALLAO','AV. REP DE PANAMÁ 121'),
('SAN ISIDRO','AV. AUGUSTO P. ARANIBAR 1991'),
('BELLAVISTA','AV. FAUCETT 1809'),
('CERCADO DE LIMA','AV. OSCAR R. BENAVIDES 2050');
SELECT 
    *
FROM
    SEDE;



CREATE TABLE CITA (
    CODCITA BIGINT PRIMARY KEY AUTO_INCREMENT,
    CLIENTE BIGINT NOT NULL,
    SEDE BIGINT NOT NULL,
    FECHA_HORA DATETIME NOT NULL,
    ESTADO INT DEFAULT 1 NOT NULL,
    LUGARATENCION INT NOT NULL
);
INSERT INTO CITA(CLIENTE,SEDE,FECHA_HORA,LUGARATENCION) VALUES
(2,2,'2019-11-05 15:00',1),
(2,1,'2019-11-11 16:00',2),
(3,1,'2019-11-20 10:00',1),
(3,1,'2019-11-21 11:00',2);
SELECT 
    *
FROM
    CITA;

ALTER TABLE PRODUCTO ADD CONSTRAINT FK_PROD_CAT FOREIGN KEY(CATPROD) REFERENCES CATEGORIAPROD(CODCAT);
ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_CLI FOREIGN KEY(CLIENTE) REFERENCES USUARIO(CODUSUARIO);
ALTER TABLE PEDIDO ADD CONSTRAINT FK_PEDIDO_SEDE FOREIGN KEY(SEDE) REFERENCES SEDE(CODSEDE);
ALTER TABLE PEDIDODETALLE ADD CONSTRAINT FK_PEDIDODET_PEDIDO FOREIGN KEY(CODPEDIDO) REFERENCES PEDIDO(CODPEDIDO);
ALTER TABLE PEDIDODETALLE ADD CONSTRAINT FK_PEDIDODET_PROD FOREIGN KEY(PRODUCTO) REFERENCES PRODUCTO(CODPROD);
ALTER TABLE CITA ADD CONSTRAINT FK_CITA_CLIENTE FOREIGN KEY (CLIENTE) REFERENCES USUARIO(CODUSUARIO);
ALTER TABLE CITA ADD CONSTRAINT FK_CITA_SEDE FOREIGN KEY(SEDE) REFERENCES SEDE(CODSEDE);



#####################PROCEDIMIENTOS ALMACENADOS#####################

DROP PROCEDURE IF EXISTS SP_VALIDAR_LOGUEO
DELIMITER $$
CREATE PROCEDURE SP_VALIDAR_LOGUEO(
P_ID VARCHAR(100),
P_PASS VARCHAR(100)
)
BEGIN
SELECT * FROM usuario WHERE (IDLOGIN=P_ID OR EMAIL=P_ID) AND PASSWORD=P_PASS;
END $$
DELIMITER ;
CALL SP_VALIDAR_LOGUEO('HREINOSO','1234567890');
CALL SP_VALIDAR_LOGUEO('HDRF1993@OUTLOOK.COM','1234567890');
CALL SP_VALIDAR_LOGUEO('HREINOSO','456489');
CALL SP_VALIDAR_LOGUEO('HDRF1993@OUTLOOK.COM','FDSAIJI');
CALL SP_VALIDAR_LOGUEO('JFKDSJAF','1234567890');


DROP PROCEDURE IF EXISTS SP_REGISTRAR_USUARIO;
delimiter $$
CREATE procedure SP_REGISTRAR_USUARIO(
P_NOMUSUARIO 	VARCHAR(100),
P_APEUSUARIO 	VARCHAR(100),
P_DIRECCION 	VARCHAR(200),
P_DNI 			CHAR(8),
P_SEXO 			INT,
P_FECNAC 		DATE,
P_EMAIL 		VARCHAR(100),
P_TELEFONO 		VARCHAR(20),
P_IDLOGIN 		VARCHAR(100),
P_PASSWORD 		CHAR(10))
begin
INSERT INTO USUARIO
           (NOMUSUARIO
           ,APEUSUARIO
           ,DIRECCION
           ,DNI
           ,SEXO
           ,FECNAC
           ,EMAIL
           ,TELEFONO
           ,IDLOGIN
           ,PASSWORD)
     VALUES
           (P_NOMUSUARIO
           ,P_APEUSUARIO
           ,P_DIRECCION 
           ,P_DNI 		
           ,P_SEXO 		
           ,P_FECNAC 	
           ,P_EMAIL 	
           ,P_TELEFONO 	
           ,P_IDLOGIN 	
           ,P_PASSWORD);
           
end $$
delimiter ; 
call SP_REGISTRAR_USUARIO('RALLY','FLORES','AV COLONIAL 2050','78948849',1,'19930601','HREINOSOFLORES@GMAIL.COM','3672297','RFLORES','1234567890');

DROP PROCEDURE IF EXISTS SP_EDITAR_USUARIO;
delimiter $$
CREATE procedure SP_EDITAR_USUARIO(
P_CODUSUARIO 	BIGINT,     					
P_DIRECCION 	VARCHAR(200),					
P_EMAIL 		VARCHAR(100),
P_TELEFONO 		VARCHAR(20),
P_IDLOGIN 		VARCHAR(100),
P_PASSWORD 		CHAR(10))
begin
UPDATE USUARIO SET 
DIRECCION = 		P_DIRECCION 
,EMAIL = 			P_EMAIL 	
,TELEFONO = 		P_TELEFONO 	
,IDLOGIN = 			P_IDLOGIN 	
,PASSWORD = 		P_PASSWORD 	
 WHERE CODUSUARIO = P_CODUSUARIO;
end $$
delimiter ; 
call SP_EDITAR_USUARIO(4,'AV COLONIAL 322','RFLORES@OUTLOOK.COM','3672297','RFLORES','1234567890');



DROP PROCEDURE IF EXISTS SP_REGISTRAR_CITA;
delimiter $$
CREATE procedure SP_REGISTRAR_CITA(
P_CLIENTE 		BIGINT,
P_SEDE 			BIGINT,
P_FECHA_HORA 		DATETIME,
P_LUGARATENCION 	INT)
begin
INSERT INTO CITA
           (CLIENTE
           ,SEDE
           ,FECHA_HORA
           ,LUGARATENCION)
     VALUES(
           P_CLIENTE 		
           ,P_SEDE 			
           ,P_FECHA_HORA 	
           ,P_LUGARATENCION);
           
           
           
end $$
delimiter ;
call SP_REGISTRAR_CITA (2,1,'2019-11-05 16:00',1);


DROP VIEW IF EXISTS VW_CITA_TUNEADO;
CREATE VIEW VW_CITA_TUNEADO
AS
SELECT C.CODCITA AS 'NRO_CITA',U.CODUSUARIO,concat(U.NOMUSUARIO,' ',U.APEUSUARIO) AS 'NOM_CLIENTE',U.DNI AS 'DNI',U.DIRECCION AS 'DOMICILIO',U.EMAIL AS 'CORREO',U.TELEFONO AS 'TELEFONO',S.REFSEDE AS 'SEDE',date_format(fecha_hora,'%d/%m/%Y') as 'FECHA',substring(date_format(fecha_hora,'%T'),1,5) as 'HORA',CASE WHEN C.ESTADO=1 THEN 'SOLICITADO' WHEN C.ESTADO=2 THEN 'ATENDIDO' WHEN C.ESTADO=3 THEN 'CANCELADO' END AS 'ESTADO_ACTUAL',CASE WHEN C.LUGARATENCION=1 THEN 'EN SEDE' WHEN C.LUGARATENCION=2 THEN 'A DOMICILIO' END AS 'LUGAR_ATENCION' FROM CITA C JOIN USUARIO U ON C.CLIENTE=U.CODUSUARIO JOIN SEDE S ON C.SEDE=S.CODSEDE;

SELECT 
    *
FROM
    VW_CITA_TUNEADO;

DROP PROCEDURE IF EXISTS SP_REGISTRAR_PEDIDO_CABECERA;
delimiter $$
CREATE procedure SP_REGISTRAR_PEDIDO_CABECERA(
P_CLIENTE 		BIGINT,
P_FECPEDIDO 	DATETIME,
P_SEDE 			BIGINT,
P_METODOENVIO 	INT,
P_METODOPAGO 	INT,
P_MONTO 		NUMERIC(19,6))
begin
INSERT INTO PEDIDO
           (CLIENTE
           ,FECPEDIDO
           ,SEDE
           ,METODOENVIO
           ,METODOPAGO
           ,MONTO)
     VALUES
           (P_CLIENTE 		
           ,P_FECPEDIDO 	
           ,P_SEDE 			
           ,P_METODOENVIO 	
           ,P_METODOPAGO 	
           ,P_MONTO 	);	
           
end $$
delimiter ;
call SP_REGISTRAR_PEDIDO_CABECERA (3,'2019-11-05 15:50',1,1,1,34.00);


DROP PROCEDURE IF EXISTS SP_REGISTRAR_PEDIDO_DETALLE;
delimiter $$
CREATE procedure SP_REGISTRAR_PEDIDO_DETALLE(
P_CODPEDIDO 	BIGINT,
P_PRODUCTO 		BIGINT,
P_CANTIDAD 		INT,
P_MONTO 		NUMERIC(19,6))
begin
INSERT INTO PEDIDODETALLE
           (CODPEDIDO
           ,PRODUCTO
           ,CANTIDAD
           ,MONTO)
     VALUES
           (P_CODPEDIDO 
           ,P_PRODUCTO 	
           ,P_CANTIDAD 	
           ,P_MONTO 	);

end $$
delimiter ;
call SP_REGISTRAR_PEDIDO_DETALLE (5,1,1,17.00);
call SP_REGISTRAR_PEDIDO_DETALLE (5,2,1,17.00);


DROP PROCEDURE IF EXISTS SP_AUTOGENERA_PEDIDO;
delimiter $$
CREATE procedure SP_AUTOGENERA_PEDIDO()
begin
SELECT  CODPEDIDO FROM PEDIDO ORDER BY CODPEDIDO DESC limit 1;
end $$
delimiter ;
call SP_AUTOGENERA_PEDIDO;


DROP PROCEDURE IF EXISTS SP_LISTAR_PRODUCTO;
delimiter $$
CREATE procedure SP_LISTAR_PRODUCTO(
TIPO_USUARIO INT,
P_CATPROD BIGINT,
P_DESCPROD VARCHAR(100))
BEGIN
IF TIPO_USUARIO=1 THEN
SELECT * FROM PRODUCTO WHERE CATPROD=P_CATPROD AND DESCPROD LIKE concat('%',P_DESCPROD, '%');
ELSE
SELECT * FROM PRODUCTO WHERE STKPROD>0 AND CATPROD=P_CATPROD AND DESCPROD LIKE concat('%',P_DESCPROD, '%');
END IF;
END $$
delimiter ;

call SP_LISTAR_PRODUCTO(1,1,'');
call SP_LISTAR_PRODUCTO(2,1,'');
call SP_LISTAR_PRODUCTO(1,1,'DENTAL');

DROP PROCEDURE IF EXISTS SP_REGISTRAR_PRODUCTO;
delimiter $$
CREATE PROCEDURE SP_REGISTRAR_PRODUCTO(
P_DESCPROD  	VARCHAR(100),
P_PREPROD 		NUMERIC(19,6),
P_STKPROD 		INT,
P_FOTOPROD 		VARCHAR(100),
P_CATPROD 		BIGINT)
begin
INSERT INTO PRODUCTO
           (DESCPROD
           ,PREPROD
           ,STKPROD
           ,FOTOPROD
           ,CATPROD)
     VALUES(
           P_DESCPROD  
           ,P_PREPROD 	
           ,P_STKPROD 	
           ,P_FOTOPROD 	
           ,P_CATPROD );	
end $$
delimiter ;
call SP_REGISTRAR_PRODUCTO('GALLETITAS DE PESCADO',25.00,100,'-',1);

DROP PROCEDURE IF EXISTS SP_EDITAR_PRODUCTO;
delimiter $$
CREATE PROCEDURE SP_EDITAR_PRODUCTO(
P_CODPROD 		BIGINT,
P_DESCPROD 		VARCHAR(100),
P_PREPROD 		NUMERIC(19,6),
P_STKPROD 		INT,
P_FOTOPROD 		VARCHAR(100),
P_CATPROD 		BIGINT)
begin
UPDATE PRODUCTO
   SET DESCPROD = P_DESCPROD 	
      ,PREPROD =  P_PREPROD 	
      ,STKPROD =  P_STKPROD 	
	  ,FOTOPROD = P_FOTOPROD 	
      ,CATPROD =  P_CATPROD 	 
 WHERE CODPROD=P_CODPROD;
 end $$
delimiter;
call SP_EDITAR_PRODUCTO(8,'GALLETITAS DE PESCADO',25.00,100,'PROD8.JPEG',1);


DROP PROCEDURE IF EXISTS SP_AUTOGENERA_PRODUCTO;
delimiter $$
CREATE procedure SP_AUTOGENERA_PRODUCTO()
begin
SELECT  CODPROD+1 FROM PRODUCTO ORDER BY CODPROD DESC limit 1;
end $$
delimiter ;

call SP_AUTOGENERA_PRODUCTO();

DROP VIEW IF EXISTS VW_PEDIDO_TUNEADO;
CREATE VIEW VW_PEDIDO_TUNEADO
AS
SELECT P.CODPEDIDO,U.CODUSUARIO,concat(U.NOMUSUARIO,' ',U.APEUSUARIO) AS 'CLIENTE',U.DNI,U.DIRECCION AS 'DOMICILIO',U.EMAIL AS 'CORREO',U.TELEFONO,date_format(FECPEDIDO,'%d/%m/%Y') as 'FECHA',substring(date_format(FECPEDIDO,'%T'),1,5) as 'HORA',S.REFSEDE,CASE WHEN P.METODOENVIO=1 THEN 'DOMICILIO' WHEN P.METODOENVIO=2 THEN 'RECOJO EN TIENDA' END AS 'METODOENVIO',CASE WHEN P.METODOPAGO=1 THEN 'EFECTIVO' WHEN P.METODOPAGO=2 THEN 'TARJETA' WHEN P.METODOPAGO=3 THEN 'DEPOSITO BANCARIO' END AS 'METODOPAGO',P.MONTO FROM PEDIDO AS P JOIN USUARIO AS U ON P.CLIENTE=U.CODUSUARIO JOIN SEDE AS S ON P.SEDE=S.CODSEDE;

SELECT 
    *
FROM
    VW_PEDIDO_TUNEADO
;
